### ISSUE TITLE
Continues sliding instead of rewind

### ISSUE THREAD

**Issue by aguieb** [CSS-Tricks/MovingBoxes#40] opened 2011-11-03 18:51 UTC
First of all, I want to thank you for posting your code online. It’s been very useful for me my learning curve to understand Jquery.

What I am posting is not an issue but just wanted to see if this is doable.

According to your latest fix when the wrap option is set to true the scrolling image will rewind to the first image.

Question: Instead of a rewind look and feel, is it possible just to continue looping the image so it seems streamless?

Any thoughts?

**Comment by Mottie** [comment] 2011-11-03 20:31
Hi @aguieb!

Actually it is possible and I've been working on this addition (on and off). I'm having a problem with a few bugs that occur when dynamically adding or removing panels. So, please stay tuned.

On another note, this feature request is actually a duplicate of [issue #28](https://github.com/chriscoyier/MovingBoxes/issues/28), so I'm going to close it. Thanks for sharing though :)

**Closed as completed by Mottie** 2011-11-03 20:31 UTC
Labels: Enhancement
