### ISSUE TITLE
Initialization

### ISSUE THREAD

**Issue by andrewjknox** [CSS-Tricks/MovingBoxes#57] opened 2012-01-03 16:51 UTC
Hi there,
I have multiple sliders on a page (8) and I seem to be having an issue knowing when they're all "fully" initialized.

I've tapped into the event for this, but like you say, sometimes, the animation events can happen after. For me, it seems to always happen when I've got at least one panel inside a slider.

No problem as I'm writing meta data onto the slider html nodes for both sets of events so I know when they've fired for that slider, but sometimes the animation events fire "twice" for each slider when after it is initialized - doesn't happen every time so I can't predict it.

I don't know if you've come across this issue before? I just need to know when all the sliders have settled so I can perform a custom action with them based on the url.

Cheers,
Andrew

**Comment by Mottie** [comment] 2012-01-03 17:21
Hi Andrew!

Hmm, the only time I've ever had a problem with callbacks is when I trigger another callback inside... then we get a nice infinite loop of events.

Maybe if you shared a link to the page you're working on or even an example of the issue you're having - modify [this demo](http://jsfiddle.net/Mottie/r6yWC/) - it would help. You probably don't need to include all eight sliders.

**Comment by andrewjknox** [comment] 2012-01-03 19:07
Hi Rob,
Thanks for the swift response, really appreciated.

I'm struggling to reproduce this but I've noticed if I slow the speed of movement in my code, it's not firing off duplicate completed events.

If I put an extremely quick speed in on that demo (got mine at http://jsfiddle.net/andrewjknox/SJJZB/9/), I can get it to fire one extra completed event. My page is quite asset heavy and I noticed that it only seems to fire extra events in between the last set of completed events and any http requests that go out after them.

That demo of mine has 3 sliders, one of which doesn't have any panels. On a slow speed, it's fires two completed events. On a really quick one, it fires three. I don't need it to be that fast but it did cause the issue I'm having :)

The hunt goes on, I feel this is going to be a late one for me :)

**Comment by Mottie** [comment] 2012-01-03 22:26
Hi Andrew!

Ok, I found the problem... I'll include it in the next update. It's going to have a few changes like removing the `width` and `panelWidth` options and having those values be set in the css, so once I make sure there aren't any bugs I'll update the plugin.

Thanks for reporting this issue!

**Comment by andrewjknox** [comment] 2012-01-04 09:19
Hey Rob,
Phew :) Thank you so much for this looking into this so quickly. I don't suppose you've got a rough idea of when this update will get posted (assuming no bugs!) - trying to work out if I should code around this or carry on with other functionality I need to have ready in a week or two.

Cheers,
Andrew

**Comment by Mottie** [comment] 2012-01-04 23:19
Ok sorry for the wait, this should now be fixed in v2.2.2.

**Comment by andrewjknox** [comment] 2012-01-07 00:48
Hi Rob,
Just wanted to say cheers for sorting that out so quickly, much appreciated! Not getting duplicate events any more.

I guess the only issue I have is trying to figure out when animation 'and' initialization is complete as sometimes I can't pick up the animation complete event - that only happens some of the time after the slider has raised it initialized event.

**Comment by Mottie** [comment] 2012-01-07 05:37
Is there a specific case that you're noticing the animation complete not firing? It would really help if you could provide a demo.

**Comment by andrewjknox** [comment] 2012-01-07 10:51
This is only on page load for the record. You mention in the docs that sometimes the completed event can occur after initialization so I assumed that's just something I'll have to deal with and this isn't a bug :) My demo is at http://jsfiddle.net/andrewjknox/SJJZB/20/ - I just do a console.log in the completed event and re-run/refresh the page - sometimes they fire, sometimes they don't but I believe this is as expected.

Animation event always fires once page loads in and I start moving the panels no problem.

For me it seems to be a timing issue - I've brought the speed up to one second and I don't (tried about 100 times testing it!) get any completed events when the page loads in so am fine with that. Just means I can keep track of a total number of sliders on page against total slider initialized events and then I know everythings in place.

**Comment by Mottie** [comment] 2012-01-10 13:59
Ok, I finally found the issue and I fixed it in the latest version (v2.2.3), I hope ;)

**Comment by andrewjknox** [comment] 2012-01-10 14:09
Absolutely awesome. I'll give that a test drive when I get a chance later on today. I'm definitely putting your excellent slider through some seriously extreme usage :)

**Comment by andrewjknox** [comment] 2012-01-10 16:15
You must hate me :)

I seem to have found an issue where the last element in the slider scrolls too far when it's set up for infinite scrolling. As in, you start on the first element and scroll left. The element comes in too far to the right by what looks to be about 50% of it's width. It happens on your demo's too.

Sorry ;)

**Comment by Mottie** [comment] 2012-01-10 16:42
Hey!

Naw, I don't hate you for helping me find bugs :P

But, are you sure your browser cache is updated? I just looked at the [main demo](http://chriscoyier.github.com/MovingBoxes/#&slider1=7&slider2=5) and everything seems fine.

**Comment by Mottie** [comment] 2012-01-10 16:52
Opps, nevermind.. I see what you mean. Fixing it here in a minute.

**Comment by andrewjknox** [comment] 2012-01-10 16:52
Hmm, strange - I've flushed cache and still happens (only noticed as it was happening on my dev box on a different machine) - that link in your post above starts off with the top slider at the end panel. If I scroll forward once, then back, that image of the cat isn't central like it was at the start.

**Comment by Mottie** [comment] 2012-01-10 16:57
LOL no I forgot to flush my cache :P

Fixed in v2.2.4. Thanks!

**Comment by andrewjknox** [comment] 2012-01-10 17:02
Lol, no probs :)

**Comment by andrewjknox** [comment] 2012-01-10 17:52
Me again :D

I seem to have a problem since v2.2.3 where I can't initialize the sliders one by one. This used to work prior to this release. I've got a wee code snippet up at: http://jsfiddle.net/andrewjknox/SJJZB/24/ where this is replicated (unless I'm doing something stupid). It applies the first movingbox slider, gets the initialization event, applies the next slider but I never get another initialized event back meaning the cycle stops.

Don't suppose you've any ideas?

**Comment by Mottie** [comment] 2012-01-10 19:04
Hmmm, I think the issue is that the `initialized` callback uses the `$(window).load(function(){});` to finish it's initialization. So, by the time the second slider is initialized, the window load function has finished. I guess I could change it, but then I fear the other callbacks may be triggered... I'll test it out when I get a chance.

**Comment by andrewjknox** [comment] 2012-01-11 03:45
Ahh yes, I see that change. The reason I ended up loading the sliders one by one was to prevent loads of animation of large assets happening at one time, and I also prioritize the order of the initialization depending on the url the user comes in on, animating that too up to the top of the screen.

For now, I've integrated your 2.2.3 change with regards to the initAnimation option as I found that really useful into my custom 2.2.2 version and all is sweet :)

**Comment by Mottie** [comment] 2012-01-13 14:10
Ok, I've moved that code out of the window load function, it now works nicely because of the flag added to the update and change functions that prevent callbacks from being triggered.

Thanks again for all the feedback! :)

**Closed as completed by Mottie** 2012-01-13 14:10 UTC
Labels: Bug
