### ISSUE TITLE
IE ONLY - slow animation if single clicked, fine if double clicked

### ISSUE THREAD

**Issue by ofwalking** [CSS-Tricks/MovingBoxes#14] opened 2011-03-09 17:33 UTC
I'm having an IE only issue since the update in version 1.7 (v.1.5 doesn't have this issue). I'm using the following settings... width to 960, panelWidth to 1, reducedSize to 1, and imageRatio to 1. 

In IE 7 and 8 the animations are really slow, if they slide at all, although I find that they work fine if the link is double clicked instead of single clicked.

**Comment by Mottie** [comment] 2011-03-10 15:05
Hi ofwalking!

I recently updated to IE9 and I don't have the older versions to test this issue. Even when I run IE9 in compatibility mode, I don't see a problme with slow animations. Try version 1.6.3 and see if the issue is gone. If so, then it's most likely due to switching the positioning of the panels from using "left" to "scrollLeft" to bypass an issue with jQuery (http://bugs.jquery.com/ticket/7193) which was fixed in jQuery 1.5.

**Comment by Mottie** [comment] 2011-03-11 15:20
Hi ofwalking!

Version 2.0 is now available. The amount of scripting to animate the panels has been reduced so hopefully that will speed up the older IE versions.

**Comment by fgosfacdjtq** [comment] 2011-03-14 22:57
I'm using IE 8.0.7600... and I can confirm that the new version (http://chriscoyier.github.com/MovingBoxes/#&slider1=4&slider2=3) scrolls at an appropriate speed.  Double-clicking the next or previous buttons doesn't change the speed of the scrolling.

**Comment by Mottie** [comment] 2011-03-15 02:37
Oh good, so this issue is resolved? :P

**Comment by Mottie** [comment] 2011-03-31 13:32
Closing issue... guessing it's been resolved

**Closed as completed by Mottie** 2011-03-31 13:32 UTC
Labels: Enhancement, Bug

**Comment by ofwalking** [comment] 2011-03-31 17:04
Yes it has, thanks. That fix did the trick.
